/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GrupoGroupNumberRouteImport } from './routes/grupo.$groupNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrupoGroupNumberRoute = GrupoGroupNumberRouteImport.update({
  id: '/grupo/$groupNumber',
  path: '/grupo/$groupNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grupo/$groupNumber': typeof GrupoGroupNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grupo/$groupNumber': typeof GrupoGroupNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grupo/$groupNumber': typeof GrupoGroupNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grupo/$groupNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grupo/$groupNumber'
  id: '__root__' | '/' | '/grupo/$groupNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GrupoGroupNumberRoute: typeof GrupoGroupNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupo/$groupNumber': {
      id: '/grupo/$groupNumber'
      path: '/grupo/$groupNumber'
      fullPath: '/grupo/$groupNumber'
      preLoaderRoute: typeof GrupoGroupNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GrupoGroupNumberRoute: GrupoGroupNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
